name: CICD

on:
    push:
        branches:
          - 'master'
        paths:
          - .github/workflows/CICD.yml
          - tee2/**

env:
    IMAGE: ${{ vars.NCR_REGISTRY }}/tee2-app
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/tee2-app:latest

jobs:
    build-and-push:
        name: Build and Push Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: test
              run: |
                docker-compose up --build -d
                docker-compose run tee2-app python manage.py test
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY_ID }}
                password: ${{ secrets.NCR_SECRET_KEY }}

            - name: Get current timestamp
              id: timestamp
              run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: lion_app
                tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
                push: true

    deploy:
        needs: build-and-push
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: pull and run the image
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    docker login \
                    ${{ vars.NCR_REGISTRY }} \
                    -u ${{ secrets.NCR_ACCESS_KEY_ID }} \
                    -p ${{ secrets.NCR_SECRET_KEY }}
                    docker pull ${{ env.IMAGE_TAG }}
                    docker stop tee2-app && docker rm tee2-app
                    docker run -p 8000:8000 -d \
                    --name tee2-app \
                    -v ~/.aws:/root/.aws:ro \
                    --env-file .env \
                    lion-cr.kr.ncr.ntruss.com/tee2-app:latest
            - name: echo IMAGE_TAG
              run: echo $IMAGE_TAG